
deploy: |
  echo "Running deploy hooks from hooks.yml in the $DEVSHOP_ENVIRONMENT environment for the $DEVSHOP_PROJECT..."

  composer yaml-tests --tests-file=deploy.yml --ansi

  echo "Environment Variables:"
  env

# Fires after "Run Tests" task.
test: |
  echo "Running test hooks from hooks.yml in the $DEVSHOP_ENVIRONMENT environment for the $DEVSHOP_PROJECT..."
  composer yaml-tests --ansi
